#!/usr/bin/env node
/*!
 * tools/build-links.js — turns the JSON files in a data directory into the
 * permanent, printable URLs the project promises.
 *
 * A QR code has to encode a URL that never changes. On a static host that means
 * one real file per username, so this generates:
 *
 *   profile-data/index.json    the manifest listProfiles() reads (a static site
 *                              cannot list a directory)
 *   c/<username>/index.html    a tiny stub that boots the profile renderer
 *   c/index.html               every card on this deployment
 *
 * Each stub is ~14 lines: it sets the username and loads the SAME app that
 * /profile/ runs. No duplicated renderer, no per-user code.
 *
 * Stubs are gitignored — they are derived, and a deleted profile should not leave
 * a stale URL behind. 404.html boots the same app for any path, so a deployment
 * that never runs this tool still works.
 *
 * Usage:
 *   node tools/build-links.js                  build profile-data/ into c/
 *   node tools/build-links.js --check          CI: fail if the manifest is stale
 *   node tools/build-links.js --data examples  rebuild an example set
 *   node tools/build-links.js --clean          remove generated stubs
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const USERNAME_RE = /^[a-z0-9_.-]{3,32}$/i;

function args(argv) {
  const out = { data: 'profile-data', out: 'c', check: false, clean: false, quiet: false, manifestOnly: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') out.check = true;
    else if (a === '--manifest-only') out.manifestOnly = true;
    else if (a === '--clean') out.clean = true;
    else if (a === '--quiet' || a === '-q') out.quiet = true;
    else if (a === '--data') out.data = argv[++i];
    else if (a === '--out') out.out = argv[++i];
    else if (a === '--help' || a === '-h') out.help = true;
  }
  return out;
}

/** Profile JSON files in a data directory, by username. */
function readProfiles(dataDir) {
  if (!fs.existsSync(dataDir)) return { profiles: [], errors: [`no such directory: ${dataDir}`] };
  const errors = [];
  // Registry and manifest files live beside the profiles but are not profiles.
  // Without this, tokens.json would be published as a person called "tokens".
  const NOT_PROFILES = new Set(['index.json', 'tokens.json', 'followers.json']);
  const profiles = fs.readdirSync(dataDir)
    .filter((f) => f.endsWith('.json') && !NOT_PROFILES.has(f) && !f.startsWith('_'))
    .sort()
    .map((file) => {
      const nameFromFile = file.replace(/\.json$/, '');
      let json;
      try {
        json = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
      } catch (err) {
        errors.push(`${file}: not valid JSON (${err.message})`);
        return null;
      }
      if (!USERNAME_RE.test(nameFromFile)) {
        errors.push(`${file}: filename must be a valid username (3-32 chars, letters digits . _ -)`);
        return null;
      }
      if (json.username && json.username !== nameFromFile) {
        errors.push(`${file}: "username" is "${json.username}" but the file is named "${nameFromFile}" — ` +
          'they must match, because the URL is /c/<filename>/');
        return null;
      }
      if (!json.username) json.username = nameFromFile;
      return { file, username: json.username, json };
    })
    .filter(Boolean);
  return { profiles, errors };
}

/**
 * The stub that makes /c/<username>/ a real URL.
 *
 * Everything is relative to the stub's own directory, and the renderer works out
 * the climb back to the site root itself (Store.rootRelative), so this file is
 * identical no matter where the site is deployed.
 */
function stubHtml(username, displayName) {
  const title = (displayName || username) + ' — QR Link Card';
  const safe = String(username).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<link rel="stylesheet" href="../../assets/styles.css">
</head>
<!--
  Generated by tools/build-links.js — do not edit.
  This stub exists so that ${safe}'s permanent URL, /c/${safe}/, is a real file on
  a static host. It runs the same renderer as /profile/?u=${safe}.
-->
<body data-username="${safe}" class="profile-page">
<script src="../../lib/qr.js"></script>
<script src="../../card-templates/card-templates.js"></script>
<script src="../../lib/access.js"></script>
<script src="../../lib/store.js"></script>
<script src="../../profile/profile.js"></script>
<script src="../../profile/boot.js"></script>
</body>
</html>
`;
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/** The manifest listProfiles() reads, plus the fields the index page shows. */
function manifest(profiles) {
  return {
    $comment: [
      'Generated by tools/build-links.js — do not edit by hand.',
      'A static site cannot list a directory, so this is how the index page finds',
      'every card. Run `npm run build` after adding or renaming a profile.'
    ],
    generated_at: new Date().toISOString().slice(0, 10),
    count: profiles.length,
    profiles: profiles.map((p) => p.username)
  };
}

/** /c/ landing page: every card on this deployment, grouped by whether it is real. */
function directoryHtml(profiles) {
  const rows = profiles.map((p) => {
    const j = p.json;
    const links = (j.links || []).length;
    const starter = j._starter ? '<span class="pill pill-muted">starter — edit me</span>' : '';
    return `    <li class="card-row">
      <a href="${encodeURIComponent(p.username)}/">
        <span class="card-row-name">${escapeHtml(j.display_name || p.username)}</span>
        <span class="card-row-role">${escapeHtml(j.designation || '')}</span>
        <span class="card-row-meta">${links} link${links === 1 ? '' : 's'} ${starter}</span>
      </a>
    </li>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>All cards — QR Link Card</title>
<link rel="stylesheet" href="../assets/styles.css">
</head>
<!-- Generated by tools/build-links.js — do not edit. -->
<body>
<a class="sr-only" href="#main">Skip to content</a>

<header class="topbar">
  <a class="brand" href="../index.html">
    <svg width="22" height="22" viewBox="0 0 22 22" aria-hidden="true">
      <rect width="22" height="22" rx="5" fill="#16161d"></rect>
      <rect x="4" y="4" width="5" height="5" fill="#f2b134"></rect>
      <rect x="13" y="4" width="5" height="5" fill="#fff"></rect>
      <rect x="4" y="13" width="5" height="5" fill="#fff"></rect>
      <rect x="13" y="13" width="2" height="2" fill="#fff"></rect>
      <rect x="16" y="16" width="2" height="2" fill="#f2b134"></rect>
    </svg>
    QR Link Card
  </a>
  <nav>
    <a href="../index.html">Cards</a>
    <a href="../card-builder/">Builder</a>
    <a href="../dashboard/">Dashboard</a>
    <a href="../templates/">Templates</a>
  </nav>
</header>

<main id="main">
  <div class="wrap narrow">
    <h1>Every card on this site</h1>
    <p class="muted">Each of these is a permanent URL, <code>/c/&lt;username&gt;/</code>, generated from one
      JSON file in <code>profile-data/</code>. This page is generated too — run
      <code>npm run build</code> after adding a profile.</p>

    <ul class="card-list">
${rows || '      <li class="muted">No profiles yet. Add <code>profile-data/yourname.json</code>.</li>'}
    </ul>
  </div>
</main>

<script src="../lib/store.js"></script>
<script src="../lib/access.js"></script>
</body>
</html>
`;
}

function writeIfChanged(file, contents) {
  const before = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  // Dates would make every run look like a change; compare without them.
  const strip = (t) => (t == null ? null : t.replace(/generated_at.*/g, ''));
  if (strip(before) === strip(contents)) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents, 'utf8');
  return true;
}

function removeStubs(outDir, keep) {
  if (!fs.existsSync(outDir)) return [];
  const removed = [];
  fs.readdirSync(outDir).forEach((entry) => {
    if (entry === 'index.html') return;
    const dir = path.join(outDir, entry);
    if (!fs.statSync(dir).isDirectory()) return;
    if (keep.has(entry)) return;
    fs.rmSync(dir, { recursive: true, force: true });
    removed.push(entry);
  });
  return removed;
}

function main(argv) {
  const opts = args(argv || process.argv.slice(2));
  if (opts.help) {
    console.log('Usage: node tools/build-links.js [--check] [--clean] [--manifest-only] [--data DIR] [--out DIR] [--quiet]');
    return 0;
  }

  const dataDir = path.resolve(ROOT, opts.data);
  const outDir = path.resolve(ROOT, opts.out);
  const { profiles, errors } = readProfiles(dataDir);

  if (errors.length) {
    console.error(`build-links: ${errors.length} problem(s) in ${opts.data}/`);
    errors.forEach((e) => console.error('  ✗ ' + e));
    return 1;
  }

  if (opts.clean) {
    const removed = removeStubs(outDir, new Set());
    if (!opts.quiet) console.log(`Removed ${removed.length} generated stub(s) from ${opts.out}/`);
    return 0;
  }

  const manifestFile = path.join(dataDir, 'index.json');
  const manifestText = JSON.stringify(manifest(profiles), null, 2) + '\n';
  const directoryFile = path.join(outDir, 'index.html');
  const directoryText = directoryHtml(profiles);

  if (opts.check) {
    let stale = false;
    const current = fs.existsSync(manifestFile) ? fs.readFileSync(manifestFile, 'utf8') : null;
    const strip = (t) => (t == null ? null : t.replace(/generated_at.*/g, ''));
    if (strip(current) !== strip(manifestText)) {
      stale = true;
      console.error(`${opts.data}/index.json is out of date.`);
      console.error(`  On disk: ${profiles.map((p) => p.username).join(', ') || '(none)'}`);
      if (current) {
        try {
          const listed = JSON.parse(current).profiles || [];
          const onDisk = new Set(profiles.map((p) => p.username));
          listed.filter((u) => !onDisk.has(u)).forEach((u) => console.error(`  listed but missing: ${u}.json`));
          profiles.filter((p) => !listed.includes(p.username))
            .forEach((p) => console.error(`  new, not listed: ${p.username}.json`));
        } catch (e) { /* reported above */ }
      }
      console.error('  Run: npm run build');
    }
    if (stale) return 1;
    if (!opts.quiet) {
      console.log(`${opts.data}/index.json OK: ${profiles.length} profile(s) — ` +
        profiles.map((p) => `/c/${p.username}/`).join(', '));
    }
    return 0;
  }

  const changed = [];
  if (writeIfChanged(manifestFile, manifestText)) changed.push(path.relative(ROOT, manifestFile));

  // --manifest-only is for fixture sets (examples/) that are read by a gallery
  // rather than published as /c/<username>/ URLs.
  if (opts.manifestOnly) {
    if (!opts.quiet) {
      console.log(`${opts.data}/index.json: ${profiles.length} profile(s)` +
        (changed.length ? ' (written)' : ' (already up to date)'));
    }
    return 0;
  }

  if (writeIfChanged(directoryFile, directoryText)) changed.push(path.relative(ROOT, directoryFile));

  profiles.forEach((p) => {
    const stub = path.join(outDir, p.username, 'index.html');
    if (writeIfChanged(stub, stubHtml(p.username, p.json.display_name))) {
      changed.push(path.relative(ROOT, stub));
    }
  });

  const removed = removeStubs(outDir, new Set(profiles.map((p) => p.username)));

  if (!opts.quiet) {
    console.log(`build-links: ${profiles.length} profile(s) → ${opts.out}/`);
    profiles.forEach((p) => console.log(`  ✓ /c/${p.username}/`));
    if (removed.length) console.log(`  ✗ removed stale: ${removed.join(', ')}`);
    if (changed.length) console.log(`  wrote: ${changed.join(', ')}`);
    else console.log('  nothing to do (already up to date)');
  }
  return 0;
}

if (require.main === module) process.exit(main());
module.exports = { main, readProfiles, stubHtml, manifest, directoryHtml, args };
